
package gui_textfields_checkboxes_buttons;


public class MyFrame extends javax.swing.JFrame {


    public MyFrame() {
        initComponents();
        this.setVisible(true);  //Shows Hello World
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FirstName = new javax.swing.JLabel();
        FirstNameTextField = new javax.swing.JTextField();
        LastName = new javax.swing.JLabel();
        LastNameTextField1 = new javax.swing.JTextField();
        PasswordField = new javax.swing.JPasswordField();
        PasswordLable = new javax.swing.JLabel();
        DissableLoggerOutputCheckbox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FirstName.setText("Enter First Name");
        FirstName.setToolTipText("");

        FirstNameTextField.setText("First Name");
        FirstNameTextField.setToolTipText("Enter the First Name:");
        FirstNameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                FirstNameTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                FirstNameTextFieldFocusLost(evt);
            }
        });
        FirstNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstNameTextFieldActionPerformed(evt);
            }
        });
        FirstNameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                FirstNameTextFieldKeyTyped(evt);
            }
        });

        LastName.setText("Enter Last Name");
        LastName.setToolTipText("");

        LastNameTextField1.setText("Last Name");
        LastNameTextField1.setToolTipText("Enter the Last Name:");
        LastNameTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                LastNameTextField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                LastNameTextFieldFocusLost(evt);
            }
        });
        LastNameTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                LastNameTextFieldKeyTyped(evt);
            }
        });

        PasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordFieldActionPerformed(evt);
            }
        });

        PasswordLable.setText("Password");

        DissableLoggerOutputCheckbox.setText("Dissable Output Logger Data");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(FirstName)
                        .addGap(29, 29, 29)
                        .addComponent(FirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LastName)
                            .addComponent(PasswordLable))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LastNameTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(PasswordField)))
                    .addComponent(DissableLoggerOutputCheckbox))
                .addContainerGap(236, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FirstName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LastNameTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LastName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PasswordLable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(DissableLoggerOutputCheckbox)
                .addGap(152, 152, 152))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FirstNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstNameTextFieldActionPerformed
        System.out.println("Action First Name Text Field...");
    }//GEN-LAST:event_FirstNameTextFieldActionPerformed

    private void FirstNameTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FirstNameTextFieldFocusGained
        if (this.DissableLoggerOutputCheckbox.isSelected()==false)
        System.out.println("Entered First Name Text Field...");
    }//GEN-LAST:event_FirstNameTextFieldFocusGained

    private void LastNameTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LastNameTextFieldFocusLost
        if (this.DissableLoggerOutputCheckbox.isSelected()==false)
        System.out.println("Leaving Last Name Text Field...");
    }//GEN-LAST:event_LastNameTextFieldFocusLost

    private void LastNameTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LastNameTextField1FocusGained
        if (this.DissableLoggerOutputCheckbox.isSelected()==false)
        System.out.println("Entered Last Name Text Field...");
    }//GEN-LAST:event_LastNameTextField1FocusGained

    private void FirstNameTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FirstNameTextFieldFocusLost
       if (this.DissableLoggerOutputCheckbox.isSelected()==false)
        System.out.println("Leaving First Name Text Field...");
    }//GEN-LAST:event_FirstNameTextFieldFocusLost

    private void LastNameTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LastNameTextFieldKeyTyped
        System.out.println("User typed: " +evt.getKeyChar()+" - in LastnameTextField");
    }//GEN-LAST:event_LastNameTextFieldKeyTyped

    private void PasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordFieldActionPerformed
        
    }//GEN-LAST:event_PasswordFieldActionPerformed

    private void FirstNameTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FirstNameTextFieldKeyTyped
        System.out.println("User typed: " +evt.getKeyChar()+" - in FirstnameTextField");
    }//GEN-LAST:event_FirstNameTextFieldKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox DissableLoggerOutputCheckbox;
    private javax.swing.JLabel FirstName;
    private javax.swing.JTextField FirstNameTextField;
    private javax.swing.JLabel LastName;
    private javax.swing.JTextField LastNameTextField1;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel PasswordLable;
    // End of variables declaration//GEN-END:variables
}
